easy_admin:
  site_name: "mealtime.io"
  design:
    brand_color: '#1ABC9C'
    menu:
      - { entity: 'Post', icon: 'comment' }
      - { entity: 'Project', icon: 'sitemap' }
      - { entity: 'Tag', icon: 'tags' }
      - { entity: 'TimelineEvent', icon: 'exclamation' }
      - { entity: 'TimelineEventType', icon: 'question' }
  entities:
    Project:
      class: App\Entity\Project
      label: 'Projects'
      form:
        fields:
          - 'enabled'
          - 'title'
          - 'url'
          - {property: 'description', type: 'ckeditor'}
          - 'tags'
      list:
        title: 'Projects'
    Tag:
      class: App\Entity\Tag
      label: 'Tags'
      list:
        title: 'Tags'
    TimelineEvent:
      class: App\Entity\TimelineEvent
      label: 'Events'
      form:
        fields:
          - 'enabled'
          - 'name'
          - 'date_start'
          - 'date_stop'
          - {property: 'description', type: 'ckeditor'}
          - 'type'
          - 'tags'
      list:
        title: 'Events'
    TimelineEventType:
      class: App\Entity\TimelineEventType
      label: 'EventTypes'
      list:
        title: 'EventTypes'
    Post:
      class: App\Entity\Post
      label: 'Posts'
      form:
        fields:
          - 'enabled'
          - 'type'
          - 'slug'
          - 'title'
          - 'subtitle'
          - 'image'
          - {property: 'content', type: 'ckeditor'}
          - 'url'
          - 'tags'
          - 'created'
          - 'updated'
          - 'posted'
      list:
        title: 'Posts'